name: yesod-simple-example
version: 0.1.0

flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

default-extensions:
- TemplateHaskell
- QuasiQuotes
- OverloadedStrings
- NoImplicitPrelude
- MultiParamTypeClasses
- TypeFamilies
- GADTs
- GeneralizedNewtypeDeriving
- FlexibleContexts
- FlexibleInstances
- EmptyDataDecls
- NoMonomorphismRestriction
- DeriveDataTypeable
- ViewPatterns
- TupleSections
- RecordWildCards
- CPP

library:
  source-dirs:
  - .
  - app
  exposed-modules:
    #- Application
    #- Foundation
    #- Import
    #- Import.NoFoundation
    #- Settings
    #- Settings.StaticFiles
    #- Handler.Common
    #- Handler.Home
    #- Handler.Comment
  dependencies:
  - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
  - yesod >=1.4.3 && <1.5
  - yesod-core >=1.4.30 && <1.5
  - yesod-static >=1.4.0.3 && <1.6
  - yesod-form >=1.4.0 && <1.5
  - classy-prelude >=0.10.2
  - classy-prelude-conduit >=0.10.2
  - classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1
  - bytestring >=0.9 && <0.11
  - text >=0.11 && <2.0
  - template-haskell
  - shakespeare >=2.0 && <2.1
  - hjsmin >=0.1 && <0.3
  - monad-control >=0.3 && <1.1
  - wai-extra >=3.0 && <3.1
  - yaml >=0.8 && <0.9
  - http-conduit >=2.1 && <2.3
  - directory >=1.1 && <1.4
  - warp >=3.0 && <3.3
  - data-default
  - aeson >=0.6 && <1.1
  - conduit >=1.0 && <2.0
  - monad-logger >=0.3 && <0.4
  - fast-logger >=2.2 && <2.5
  - wai-logger >=2.2 && <2.4
  - file-embed
  - safe
  - unordered-containers
  - containers
  - vector
  - time
  - case-insensitive
  - wai
  - filepath
  - foreign-store # Required because we're building app/DevelMain.hs
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  yesod-simple-example:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - yesod-simple-example
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - yesod-simple-example
    - yesod-test >=1.5.2 && <1.6
    - yesod-core
    - yesod
    - hspec >=2.0.0
    - classy-prelude
    - classy-prelude-yesod
    - aeson
