version: 2
jobs:
  build:
    docker:
      - image: steshaw/bt-build-base:0.1.20

    working_directory: /app

    steps:

      - checkout

      - run:
          name: Sync file modification times with Git commit times
          command: |
            scripts/git-sync-modification-times
            scripts/confirm-times-synchronised

      - restore_cache:
          keys:
            - dot-stack-{{checksum "stack.yaml"}}-{{checksum "yesod-simple-example.cabal"}}
            - dot-stack

      - restore_cache:
          keys:
            - dot-stack-work-{{.Branch}}-{{.Revision}}
            - dot-stack-work-{{.Branch}}
            - dot-stack-work-master

      - run:
          name: Time skew?
          command: scripts/skew

      - run:
          name: Build
          command: |
            scripts/build broken
            set -x
            du -hs ~/.stack
            du -hs .stack-work

      - save_cache:
          key: dot-stack-work-{{.Branch}}-{{.Revision}}
          paths:
            - .stack-work

      - save_cache:
          key: dot-stack-{{checksum "stack.yaml"}}-{{checksum "yesod-simple-example.cabal"}}
          paths:
            - ~/.stack
