version: 2
jobs:
  build:
    docker:
      - image: steshaw/bt-build-base:0.1.20

    working_directory: /app

    steps:

      - checkout

      - run:
          name: Sync file modification times with Git author dates
          command: |
            scripts/git-sync-modification-times
            scripts/confirm-times-synchronised

      - restore_cache:
          keys:
            - stack.packages.{{checksum "stack.yaml"}}.{{checksum "package.yaml"}}
            - stack.packages

      - restore_cache:
          keys:
            - stack.work.dist.{{.Branch}}.{{.Revision}}
            - stack.work.dist.{{.Branch}}
            - stack.work.dist.master

      - run:
          name: Clock skew?
          command: scripts/skew

      - run:
          name: Build
          command: |
            scripts/build

      - save_cache:
          key: stack.work.dist.{{.Branch}}.{{.Revision}}
          paths:
            - .stack-work/dist

      - save_cache:
          key: stack.packages.{{checksum "stack.yaml"}}.{{checksum "package.yaml"}}
          paths:
            - ~/.stack
            - .stack-work/install
