version: 2
jobs:

  build:

    docker:
      - image: steshaw/bt-build-base:0.1.19

    working_directory: /app

    steps:

      - checkout

      - run:
          name: Sync file modification times with Git commit times
          command: scripts/git-sync-modification-times

      - restore_cache:
          keys:
            - stack-{{.Branch}}-{{.Revision}}
            - stack-{{.Branch}}
            - stack-master

      - run:
          name: Build
          command: |
            scripts/build broken --system-ghc

      - save_cache:
          key: stack-{{.Branch}}-{{.Revision}}
          paths:
            - ~/.stack
            - .stack-work
