#!/usr/bin/env bash

set -euo pipefail

function p() {
  parallel --no-notice "$@"
}

git ls-files |
  p git --no-pager log -1 "--pretty=tformat:'%ad {}'" --date=format:'%s' {} |
  p --colsep ' ' touch --date=@{1} {2}
