#!/bin/bash

set -euxo pipefail

echo
date
echo
date +%s
echo
stat Makefile
echo
stat -c%Y Makefile
echo
git --no-pager log -1 Makefile
echo
git --no-pager log -1 --pretty=tformat:'%ad Makefile' --date=format:'%s' Makefile
echo
git --no-pager log -1 --pretty=tformat:'%ad Makefile' --date=iso Makefile
echo
git --no-pager log -1 '--pretty=tformat:%ad Makefile' --date=unix Makefile
echo
git --version
echo
make
